version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00" # UTC
    labels:
      - "scope: app-deps"
    commit-message:
      prefix: "chore(deps)"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00" # UTC
    labels:
      - "scope: ci-deps"
    commit-message:
      prefix: "chore(ci)"
    open-pull-requests-limit: 10
