name: CI Workflow

on:
  push:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-app:
    runs-on: macos-latest
    steps:
      - name: 'Checking out workspace, with submodules..'
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: 'Set up JDK toolchain..'
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
          cache: 'gradle'
      - name: 'Set up Android toolchain..'
        uses: android-actions/setup-android@v2
      - name: 'Setting up NDK toolchain..'
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: 'r25c'
      - name: 'Set up Xcode toolchain..'
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.2.0'
      - name: 'Set up Rust toolchain..'
        uses: actions-rs/toolchain@v1
        with:
          toolchain: '1.68.2'
          components: rustfmt
          override: true
      - name: 'Set up Flutter toolchain..'
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.11'
          cache: true
      - name: 'Set up Dart toolchain..'
        uses: dart-lang/setup-dart@v1
        with:
          sdk: '2.19.6'
      - name: 'Install `flutter_rust_bridge_codegen`..'
        uses: actions-rs/install@v0.1
        with:
          crate: flutter_rust_bridge_codegen
          version: '1.75.0'
          use-tool-cache: true
      - name: 'Download Flutter deps'
        run: flutter pub get
      - name: 'Generate Rust <-> Dart/Flutter bindings, through FFI..'
        run: flutter_rust_bridge_codegen --rust-input native/src/api.rs --dart-output lib/bridge_generated.dart --dart-decl-output lib/bridge_definitions.dart --c-output ios/Runner/bridge_generated.h --extra-c-output-path macos/Runner
