name: CI Workflow

on:
  push:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-app:
    runs-on: macos-latest
    steps:
      - name: 'Checking out workspace, with submodules..'
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: 'Setting up JDK environment..'
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
      - name: 'Setting up Android development environment..'
        uses: android-actions/setup-android@v2
      - name: 'Setting up Xcode development environment..'
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
