name: CI Workflow

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'zulu'
      - uses: android-actions/setup-android@v2
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
      - uses: gradle/gradle-build-action@v2
      - name: Build all build type and flavor permutations
        run: ./gradlew assembleDebug --stacktrace
